### ISSUE TITLE
Unable to get board type on Edgerouter X

### ISSUE THREAD

**Issue by Metalnib** [whiskerz007/ubnt_get_wireguard#3]
Hello
First let me thank you for your excellent work!
I was in the middle of writing something similar when I found your script and I adopted it immediately :) (I'm not that good as you in bash). 
I have deploed this script on several sites with different configurations and routers, so I tested it on ErX, ERLite, ER6P and ER12. Works realy nice and elegant.

There is one little issue with EdgerouterX, it's not able to detect the platform. It was easy to fix - I've committed pullrequest.

p.s. Anyway there is something else that I want to discuss, Persistency. On some of my sites i have unbound dns and I have also this script https://github.com/britannic/install-edgeos-packages
to keep persistency after firmware upgrades, but it's not on all routers. So I have two suggestions for you:
1) change FIRSTBOOT_DIR='/config/data/firstboot/install-packages'  to '/config/data/install-packages' - so both scripts could work together (I haven't tested this in practice yet, but will do it soon)
Or
2) augment the script to check the folder '/config/data/firstboot/install-packages' and in case of no internet connection to install the package from that folder. In such case we could put the script directly into post-config.d and reboot once more after WG package installation, I think this will restore the configuration.

Excuse me if something is not clear, english is not my native language.

**Comment by whiskerz007** [comment]
Please post the results of `cat /proc/cpuinfo` from your EdgeRouter X.

As for your comments on persistency, I chose to handle it according to Ubiquiti's supported firmware process. The repo you reference installs the packages after the configuration has been loaded to memory. By placing the package in `/config/data/firstboot/install-packages`, the package will be installed before the configuration is loaded into RAM, there by eliminating an additional reboot or manually load of configuration.

**Comment by Metalnib** [comment]
Here is my `cat /proc/cpuinfo`
```bash
system type		: MediaTek MT7621 ver:1 eco:3
machine			: Ubiquiti EdgeRouter
processor		: 0
cpu model		: MIPS 1004Kc V2.15
BogoMIPS		: 581.63
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 32
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa			: mips1 mips2 mips32r1 mips32r2
ASEs implemented	: mips16 dsp mt
shadow register sets	: 1
kscratch registers	: 0
package			: 0
core			: 0
VPE			: 0
VCED exceptions		: not available
VCEI exceptions		: not available

processor		: 1
cpu model		: MIPS 1004Kc V2.15
BogoMIPS		: 581.63
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 32
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa			: mips1 mips2 mips32r1 mips32r2
ASEs implemented	: mips16 dsp mt
shadow register sets	: 1
kscratch registers	: 0
package			: 0
core			: 0
VPE			: 1
VCED exceptions		: not available
VCEI exceptions		: not available

processor		: 2
cpu model		: MIPS 1004Kc V2.15
BogoMIPS		: 581.63
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 32
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa			: mips1 mips2 mips32r1 mips32r2
ASEs implemented	: mips16 dsp mt
shadow register sets	: 1
kscratch registers	: 0
package			: 0
core			: 1
VPE			: 0
VCED exceptions		: not available
VCEI exceptions		: not available

processor		: 3
cpu model		: MIPS 1004Kc V2.15
BogoMIPS		: 581.63
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 32
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa			: mips1 mips2 mips32r1 mips32r2
ASEs implemented	: mips16 dsp mt
shadow register sets	: 1
kscratch registers	: 0
package			: 0
core			: 1
VPE			: 1
VCED exceptions		: not available
VCEI exceptions		: not available
```


So by putting the package into `/config/data/firstboot/install-packages` the `EdgeOS` will have care to install this package after firmware update? This makes the script that I mention absolutely redundant!

**Comment by whiskerz007** [comment]
Please post the results from running `/usr/sbin/ubnt-hal getBoardId`.

**Comment by Metalnib** [comment]
`/usr/sbin/ubnt-hal getBoardId`  returns `e50` 

This is nice, but on Cavium routers is not e300: 
ER-12  is `e302`
ER-6P is `e301`  and no `\n` (LF)!

**Comment by whiskerz007** [comment]
Please respond with the results of running `cat /etc/version` on all the routers you have access to.

**Comment by Metalnib** [comment]
It's going to be long list :) I will prepare everything after the holidays because some of the routers are not in production yet (no remote access) and they have bigger variety of versions.

**Comment by whiskerz007** [comment]
I would only need the output of unique models. I believe I can get this information through other means, however I would like to see actual results from running hardware.

**Comment by Metalnib** [comment]
Model | Firmware | cpuinfo: sys type, cpu model | BoardId | version
-------|--------------|-------------|--------------|----------
ER-L | 2.0.6 | UBNT_E100, Cavium Octeon+ V0.1 | e102 | EdgeRouter.ER-e100.v2.0.6.5208553.190708.0607
ER-12 | 2.0.8 | UBNT_E300, Cavium Octeon III V0.2  FPU V0.0 | e302\n | EdgeRouter.ER-e300.v2.0.8.5247496.191120.1124
ER-12 | 1.10.7 | UBNT_E300, Cavium Octeon III V0.2  FPU V0.0 | e302 | EdgeRouter.ER-e300.v1.10.7.5127989.181001.1228
ER-6P | 2.0.6 | UBNT_E300, Cavium Octeon III V0.2  FPU V0.0 | e301 | EdgeRouter.ER-e300.v2.0.6.5208554.190708.0611
ER-X | 1.10.8 | MT7621, MIPS 1004Kc V2.15 | e50 | EdgeRouter.ER-e50.v1.10.8.5142457.181120.1809
ER-X | 2.0.6 | MediaTek MT7621 ver:1 eco:3, MIPS 1004Kc V2.15 | e50 | EdgeRouter.ER-e50.v2.0.6.5208541.190708.0508
ER-X | 2.0.8 | MediaTek MT7621 ver:1 eco:3, MIPS 1004Kc V2.15 | e50 | EdgeRouter.ER-e50.v2.0.8.5247496.191120.1124
-------------------------------------
It looks like `ubnt-hal getBoardId` has syntax error (no `\n`) on versions from 1.9 till 2.0.6, this is fixed in v2.0.8 on ERL and ER-12.

From all these it's clear `cat /etc/version` is reliable way to get board type.
@whiskerz007 You can remove my pullrequest and do a proper parsing of version info.
Cheers!

**Comment by whiskerz007** [comment]
I've updated the script. Please try the new version and report back your findings.

**Comment by Metalnib** [comment]
It works good, no issues found, tested on ER-X, ER-L and ER-12
