### ISSUE TITLE
Script hangs after printing WireGuard version

### ISSUE THREAD

**Issue by the-holger** [whiskerz007/ubnt_get_wireguard#5]
Hi! 
I was just trying out your script as it sounded VERY promising to keep my current setup even after a firmware upgrade. (Had a nasty surprise yesterday...)

Unfortunately it just hangs after printing the installed WireGuard version:
```
root@Router:/config/scripts# ./get_wireguard.sh
[INFO] Board model: UniFi-Gateway-3
[INFO] Board type: e120
[INFO] Board repo mapping: ugw3
[INFO] Firmware version: v4.4.50.5272448.200215.0243
[INFO] Installed WireGuard version: 0.0.20191219-2
```

Do you have any hints how I could debug this and/or contribute a fix?
In theory it should display the latest release version, right?

Thank you!
Holger

**Comment by the-holger** [comment]
After fidgeting around I think the problem is in line 138

I added some echos to see what's going on:
```
echo "BEFORE CURL"
GITHUB_RELEASES=$(curl $GITHUB_RELEASES_URL)
echo "AFTER CURL"

# Get release version
RELEASE_VERSION=${OVERRIDE_VERSION:-}
echo $RELEASE_VERSION
```

And this is the output:
```
[INFO] Board model: UniFi-Gateway-3
[INFO] Board type: e120
[INFO] Board repo mapping: ugw3
[INFO] Firmware version: v4.4.50.5272448.200215.0243
[INFO] Installed WireGuard version: 0.0.20191219-2
BEFORE CURL
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  500k  100  500k    0     0   382k      0  0:00:01  0:00:01 --:--:--  432k
AFTER CURL
```
Hanging after that.

**Comment by the-holger** [comment]
Alright, I fidgeted around some more and apparently jq is taking quite some time according to ```top``` it's been running for 6mins at 99% CPU.

Is this the expected behavior?

**Comment by whiskerz007** [comment]
That behavior is not expected. I do not have a USG to do testing with. The whole process shouldn't take more than a couple of minutes (to include downloading and installing the package). Can you tell which `jq` command is being ran. There are a few around that same point.

**Comment by whiskerz007** [comment]
Try running the following commands and see if you experience the same hang. The execution of these commands should only take a second or two.

```
$(which jq) '[.[]][0]' <(curl --silent https://api.github.com/repos/Lochnair/vyatta-wireguard/releases)
$(which jq) '[.[]][0].tag_name' <(curl --silent https://api.github.com/repos/Lochnair/vyatta-wireguard/releases)
```

**Comment by the-holger** [comment]
Thank you for your help & sorry for the late reply, I was only now able to access my USG.
The second command, i.e. getting the tag name, is done in 1.8s (and I'm behind a slowish line here):
```
admin@Router:~$ time $(which jq) '[.[]][0].tag_name' <(curl --silent https://api.github.com/repos/Lochnair/vyatta-wireguard/releases)
"0.0.20191219-2"

real	0m1.759s
user	0m0.540s
sys	0m0.220s
```

The problem is the first one, which hangs after printing the "node_id". (At least I've had it run for 10mins with no change)

```
admin@Router:~$ $(which jq) '[.[]][0]' <(curl --silent https://api.github.com/repos/Lochnair/vyatta-wireguard/releases)
{
  "body": "## For FW v2.0 download the packages named as `wireguard-v2.0...`\r\n\r\n**Note:** I'm away from home, and as such this release hasn't received any testing.\r\n\r\n**Note:** For the UGW3/4 make sure to use the latest FW with kernel 3.10.107.\r\n\r\nThis release of WireGuard for the EdgeRouter is based on upstream WireGuard snapshot [0.0.20191219](https://lists.zx2c4.com/pipermail/wireguard/2019-December/004779.html). You may download the deb attached to this release for your particular model and install it on your EdgeRouter with:\r\n\r\n    # sudo dpkg -i wireguard-<board>-0.0.20191219-2.deb\r\n\r\n## Support devices\r\n### E50\r\n* EdgeRouter X\r\n\r\n### E100\r\n* EdgeRouter Lite\r\n* EdgeRouter PoE\r\n\r\n### E200\r\n* EdgeRouter 8\r\n* EdgeRouter Pro\r\n\r\n### E300\r\n* EdgeRouter 4\r\n* EdgeRouter 6P\r\n* EdgeRouter 12\r\n\r\n### E1000\r\n* EdgeRouter Infinity\r\n\r\n### UGW3\r\n* UniFi Security Gateway\r\n\r\n### UGW4\r\n* UniFi Security Gateway Pro 4\r\n\r\n### UGWXG\r\n* UniFi Security Gateway XG 8",
  "zipball_url": "https://api.github.com/repos/Lochnair/vyatta-wireguard/zipball/0.0.20191219-2",
  "target_commitish": "master",
  "tag_name": "0.0.20191219-2",
  "node_id": "MDc6UmVsZWFzZTIyMzU3MTY1",
^C
```
In case it's relevant, my jq is version `jq-5a49c82-dirty`

PS: both commands run fine on macOS (jq-1.6) and debian (jq-1.5-1-a5b5cbe) with virtually the same execution time for both commands (0.06s for both on macOS; 1.34s/1.32s on debian)

**Comment by whiskerz007** [comment]
This would lead me to believe that the version of `jq` that Ubiquiti is using in this firmware has some issues with it. I'm not sure how to advise from this point.

**Comment by friesoft** [comment]
I'm also experiencing the same issue on my ugw3 :(
```
root@USG:/config/scripts# ./get_wireguard.sh
[INFO] Board model: UniFi-Gateway-3
[INFO] Board type: e120
[INFO] Board repo mapping: ugw3
[INFO] Firmware version: v4.4.50.5272448.200215.0243
[INFO] Installed WireGuard version: 0.0.20200318-1
```

**Comment by the-holger** [comment]
I completely agree, it seems to be a problem concerning the `jq` binary on the USG3 here.

Would it be an option for you to do the parsing of the vyatta-wireguard/releases page with a GitHub Action (if that works) and check for a file in your repository from your script? This is the only workaround I could imagine right now.

I've tried a couple of things to get jq to spit out the info we need, but had no luck whatsoever :-(

**Comment by sevengiants** [comment]
Just a guess that now more releases been put on Github, hence the USG3 jq seems not able to deal with the amount of JSON
so maybe use */releases/latest to get last one, seems quite quick return
and use */release/tag_name for OVERRIDE_VERSION?

**Comment by whiskerz007** [comment]
@sevengiants While looking into your suggestion, I developed an alternative way of running the queries that shouldn't cause the lock up. Refer to the [usg_jq_patch](https://github.com/whiskerz007/ubnt_get_wireguard/tree/usg_jq_patch) branch for the changes. If this satisfies the limitation of the USG platform, I can bring the code into the master branch. Please try this patch and report your findings.

**Comment by sevengiants** [comment]
root@USG3P:# ./get_wireguard.sh
[INFO] Board model: UniFi-Gateway-3
[INFO] Board type: e120
[INFO] Board repo mapping: ugw3
[INFO] Firmware version: v4.4.51.5287926.200408.2034
[INFO] Installed WireGuard version: 1.0.20200712-1
jq: |: No such file or directory
jq: select(.tag_name: No such file or directory
jq: ==: No such file or directory
jq: ""): No such file or directory
jq: | .tag_name: No such file or directory
[INFO] Release version:
Your installation is up to date.

**Comment by whiskerz007** [comment]
Fixes have been pushed. Please try again and report finding (both latest and specific installation methods).

**Comment by sevengiants** [comment]
> Fixes have been pushed. Please try again and report finding (both latest and specific installation methods).

apparently push is on its way for a while now, :)
as i dont see new commits on the branch

**Comment by whiskerz007** [comment]
Forgive me, I committed the changes locally and forgot to press the `push` button. It's up now, thanks for updating me.

**Comment by sevengiants** [comment]
looking good

[INFO] Board model: UniFi-Gateway-3
[INFO] Board type: e120
[INFO] Board repo mapping: ugw3
[INFO] Firmware version: v4.4.51.5287926.200408.2034
[INFO] Installed WireGuard version: 1.0.20200712-1
[INFO] Release version: 1.0.20200712-1
Your installation is up to date.

unfortunately cant test if there is a new version, will report back once new release announced

**Comment by sevengiants** [comment]
btw, i think most USG using #!/bin/bash

**Comment by whiskerz007** [comment]
> @sevengiants 
> unfortunately cant test if there is a new version, will report back once new release announced

You can install an older version by running `./get_wireguard.sh 1.0.20200623-1`. I do my testing on an ER-6P this way and have not had any issues with downgrading and upgrading. This has a potential to be problematic in the future if/when they decide to change the configuration template. When it comes to that, I'll have to look into placing notices and halting automatic operations where necessary.


> @sevengiants
> btw, i think most USG using #!/bin/bash

Although `bash` is currently located in `/bin/` on the Ubiquiti hardware, I've decided to standardize my works using `/usr/bin/env`.

**Comment by sevengiants** [comment]
Just tried, got error as
 ./get_wireguard.sh 1.0.20200623-1
[INFO] Board model: UniFi-Gateway-3
[INFO] Board type: e120
[INFO] Board repo mapping: ugw3
[INFO] Firmware version: v4.4.51.5287926.200408.2034
[INFO] Installed WireGuard version: 1.0.20200712-1
[INFO] Release version: 1.0.20200623-1
[ERROR] 0@159 Failed to locate debian package for your board and firmware.

I'd think if provide override_version, you can build a new query base URL as below
https://api.github.com/repos/WireGuard/wireguard-vyatta-ubnt/releases/tags/1.0.20200623-1

**Comment by whiskerz007** [comment]
Pushed another update to the script. Please try again and post results.

**Comment by sevengiants** [comment]
Okay, we passed getting package, it has downloaded right package.

**Comment by whiskerz007** [comment]
Has this issued been resolved with the most recent commits?

**Comment by sevengiants** [comment]
Works for me!

**Comment by the-holger** [comment]
Hey @whiskerz007 !
Wanted to chime in to say thank you! 

```
root@Router:/config/scripts# ./get_wireguard.sh
[INFO] Board model: UniFi-Gateway-3
[INFO] Board type: e120
[INFO] Board repo mapping: ugw3
[INFO] Firmware version: v4.4.51.5287926.200408.2034
[INFO] Installed WireGuard version: 1.0.20200506-1
[INFO] Release version: 1.0.20200712-1
[INFO] Debian package URL: https://github.com/WireGuard/wireguard-vyatta-ubnt/releases/download/1.0.20200712-1/ugw3-v1-v1.0.20200712-v1.0.20200513.deb
Downloading WireGuard package...
Checking WireGuard package integrity...
Backing up running configuration...
Removing running WireGuard configuration...
Removing WireGuard module...
Installing WireGuard...
^[Restoring previous running configuration...
Enabling WireGuard installation after firmware update...
WireGuard has been successfully installed.
```

Seems like it worked perfectly! Will now try to enable it to check periodically and hopefully "survive" the next USG software update without me breaking into a cold sweat :-D
