### ISSUE TITLE
Update to use Fossorest releases

### ISSUE THREAD

**Issue by farmwald** [whiskerz007/ubnt_get_wireguard#7]
The Lochnair releases seem to be out of date. https://github.com/FossoresLP/vyatta-wireguard/releases is currently on the latest wireguard release.
Could (should?) this script be updated to use Fossorest?
Thanks.

**Comment by whiskerz007** [comment]
I've change the script to point to [WireGuard/wireguard-vyatta-ubnt](https://github.com/WireGuard/wireguard-vyatta-ubnt). The WireGuard maintainers are supporting this repo.
