### ISSUE TITLE
removing old configurations failed

### ISSUE THREAD

**Issue by sevengiants** [whiskerz007/ubnt_get_wireguard#8]
just start a new issue rather than old one as this looks for me a different type of issue

[INFO] Board model: UniFi-Gateway-3
[INFO] Board type: e120
[INFO] Board repo mapping: ugw3
[INFO] Firmware version: v4.4.51.5287926.200408.2034
[INFO] Installed WireGuard version: 1.0.20200712-1
[INFO] Release version: 1.0.20200623-1
[INFO] Debian package URL: https://github.com/WireGuard/wireguard-vyatta-ubnt/releases/download/1.0.20200623-1/ugw3-v1-v1.0.20200623-v1.0.20200513.deb
Downloading WireGuard package...
Checking WireGuard package integrity...
Backing up running configuration...
Removing running WireGuard configuration...
Commit failed
[ERROR] 1@205 Unknown failure occured.

i do have two wireguard interfaces, wg0 and wg1
wg1 has route-allowed-ips true

`  msg 'Removing running WireGuard configuration...'
  vyatta_cfg_setup
  INTERFACES=( $($VYATTA_API listNodes interfaces wireguard | sed "s/'//g") )
  for INTERFACE in $INTERFACES; do
    if [ "$($VYATTA_API returnValue interfaces wireguard $INTERFACE route-allowed-ips)" == "true" ]; then
      $VYATTA_SET interfaces wireguard $INTERFACE route-allowed-ips false
      $VYATTA_COMMIT
    fi
    INTERFACE_ADDRESSES=( $(ip -oneline address show dev $INTERFACE | awk '{print $4}') )
    for IP in $($VYATTA_API returnValues interfaces wireguard $INTERFACE address | sed "s/'//g"); do
      [[ $IP != "${INTERFACE_ADDRESSES[@]}" ]] && ip address add $IP dev $INTERFACE
    done
  done
  $VYATTA_DELETE interfaces wireguard
  $VYATTA_COMMIT
  vyatta_cfg_teardown`

after hitting the error, i checked cofiguration, i can see wg0 was deleted successfully, but wg1 is still there, and route-allowed-ips still true
that's why the last commit failed at row 205 as above output at execution.
maybe the $VYATTA_SET didnt work?

then i run get_wireguard.sh <version> again, trying to see whether second run would remove my wg1
it then gets different error, i think at first run, interface address was somehow removed?
(sorry lost the log) basically it complains INTERFACE_ADDRESSES[0] invalid

**Comment by whiskerz007** [comment]
Please run `bash -x ./get_wireguard.sh` and post the entire output. Review [quoting code blocks](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) before posting.

**Comment by sevengiants** [comment]
```
++ date +%FT%T%z
+ local TIMESTAMP=2020-07-23T11:02:34+0100
+ local 'REGEX=\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]'
+ echo -e 'Removing running WireGuard configuration...'
+ tee -a /dev/fd/63
++ sed -r 's/^/2020-07-23T11:02:34+0100: /; s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g'
+ read TEXT
+ vyatta_cfg_setup
+ /opt/vyatta/sbin/my_cli_shell_api setupSession
++ /opt/vyatta/sbin/my_cli_shell_api inSession
+ INTERFACES=($($VYATTA_API listNodes interfaces wireguard | sed "s/'//g"))
++ sed 's/'\''//g'
++ /opt/vyatta/sbin/my_cli_shell_api listNodes interfaces wireguard
+ for INTERFACE in '$INTERFACES'
++ /opt/vyatta/sbin/my_cli_shell_api returnValue interfaces wireguard wg0 route-allowed-ips
+ '[' false == true ']'
+ INTERFACE_ADDRESSES=($(ip -oneline address show dev $INTERFACE | awk '{print $4}'))
++ ip -oneline address show dev wg0
++ awk '{print $4}'
++ /opt/vyatta/sbin/my_cli_shell_api returnValues interfaces wireguard wg0 address
++ sed 's/'\''//g'
+ for IP in '$($VYATTA_API returnValues interfaces wireguard $INTERFACE address | sed "s/'\''//g")'
+ [[ 192.168.20.19/24 != \1\9\2\.\1\6\8\.\2\0\.\1\9\/\2\4 ]]
+ /opt/vyatta/sbin/my_delete interfaces wireguard
+ /opt/vyatta/sbin/my_commit
++ EXIT=1
++ LINE=205
++ error_exit
++ trap - ERR
++ local 'DEFAULT=Unknown failure occured.'
++ local 'REASON=\e[97mUnknown failure occured.\e[39m'
++ local 'FLAG=\e[91m[ERROR] \e[93m1@205'
++ msg '\e[91m[ERROR] \e[93m1@205 \e[97mUnknown failure occured.\e[39m'
++ local 'TEXT=\e[91m[ERROR] \e[93m1@205 \e[97mUnknown failure occured.\e[39m'
++ echo -e '\e[91m[ERROR] \e[93m1@205 \e[97mUnknown failure occured.\e[39m'
++ log
++ read TEXT
+++ basename /config/scripts/wireguard/get_wireguard
++ local LOG_PATH=/tmp/get_wireguard.log
++ '[' '!' -f /tmp/get_wireguard.log ']'
++ local LOG_MAX_LINES=10000
++ '[' -f /tmp/get_wireguard.log ']'
+++ wc -l /tmp/get_wireguard.log
+++ cut -f1 '-d '
++ '[' 77 -ge 10000 ']'
+++ date +%FT%T%z
++ local TIMESTAMP=2020-07-23T11:02:49+0100
++ local 'REGEX=\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]'
++ tee -a /dev/fd/63
++ echo -e '[ERROR] 1@205 Unknown failure occured.'
+++ sed -r 's/^/2020-07-23T11:02:49+0100: /; s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g'
++ read TEXT
++ exit 1
+ cleanup
+ '[' '!' -z x ']'
++ /opt/vyatta/sbin/my_cli_shell_api inSession
+ vyatta_cfg_teardown
++ /opt/vyatta/sbin/my_cli_shell_api teardownSession
+ rm -rf /tmp/tmp.IdlRFG
```

**Comment by whiskerz007** [comment]
Please reboot the USG, run the previous command following a successful boot, and post the output.

**Comment by sevengiants** [comment]
find the problem when loop through the INTERFACES (array)
we need set
```  for INTERFACE in ${INTERFACES[@]}; do```

**Comment by sevengiants** [comment]
Im not quite clear about next IP address section, but seems need adjust as well

**Comment by sevengiants** [comment]
Thanks 

I do feel like ```for IP in $($VYATTA_API returnValues interfaces wireguard $INTERFACE address | sed "s/'//g");```
if ppl would have multiple addresses or even with IPv6, then this may fail into same problem as INTERFACES array

**Comment by whiskerz007** [comment]
I have both an IPv4 and IPv6 address on my WireGuard interface and the script works for me.

**Comment by whiskerz007** [comment]
Has this issued been resolved with the most recent commits?

**Comment by sevengiants** [comment]
I’d think so. I’ve set on my USG task scheduler for every 7days.
I think it’s safe to close it now
